version: 2
updates:
  - package-ecosystem: uv
    directories:
      - "/"
      - "/packages/petstore-api"
      - "/packages/petstore-web"
      - "/packages/petstore-cli"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
